# Generated by Django 5.2.17 on 2026-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_llm_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="finish_reason",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
