# Generated by Django 5.2.17 on 2026-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_raise_output_token_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="max_output_tokens",
            field=models.PositiveIntegerField(default=8192),
        ),
    ]
