# Generated by Django 5.2.17 on 2026-09-29 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_default_output_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preference", "Preference"),
                            ("fact", "Fact"),
                            ("goal", "Goal"),
                            ("context", "Context"),
                        ],
                        default="preference",
                        max_length=12,
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[("user", "You"), ("ai", "AI")],
                        default="user",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_prompt", models.TextField(blank=True)),
                ("auto_memory", models.BooleanField(default=False)),
                (
                    "default_app",
                    models.CharField(
                        choices=[
                            ("simgen", "SimGen"),
                            ("ask", "Ask"),
                            ("chat", "Chat"),
                        ],
                        default="chat",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
