"""Render a raw Claude Code session (.jsonl) as readable Markdown.

Usage: python scripts/render_transcript.py <session.jsonl> <out.md>

Keeps what a reviewer needs to follow the work: the user's messages and the assistant's replies, with each tool
call reduced to one line. Tool output, hidden reasoning and harness reminders are left out (except the user's answers to questions and plan approvals, which are kept) (the raw .jsonl next to
this file has everything). Proxy keys are redacted, and the script refuses to write if a key-like string survives.
"""
import json
import re
import sys
from datetime import datetime

from redact import KEY, leaks, redact  # noqa: E402  (same folder)
NOISE = re.compile(r"<(system-reminder|local-command-caveat|ide_opened_file|ide_selection|command-name|command-message|command-args|local-command-stdout)>.*?</\1>", re.S)
PASTE = re.compile(r"</?pasted_content[^>]*>")


def clean_user(text: str) -> str:
    text = NOISE.sub("", text)
    text = PASTE.sub("", text)
    return text.strip()


def tool_line(block: dict) -> str:
    name, inp = block.get("name", "tool"), block.get("input", {}) or {}
    detail = inp.get("description") or inp.get("file_path") or inp.get("url") or inp.get("command") or inp.get("prompt") or ""
    detail = " ".join(str(detail).split())[:140]
    return f"> tool: **{name}**" + (f" - {detail}" if detail else "")


DECISION_TOOLS = {"AskUserQuestion", "ExitPlanMode"}  # the moments where the human steered: keep their outcome


def result_text(block: dict) -> str:
    content = block.get("content")
    if isinstance(content, list):
        content = "\n".join(c.get("text", "") for c in content if isinstance(c, dict))
    return str(content or "").strip()


def decision_line(tool: str, text: str) -> str:
    if tool == "ExitPlanMode":
        return "> **User decision:** plan approved" if text.startswith("User has approved") else "> **User decision:** plan not approved"
    return "> **User answered:** " + " ".join(text.replace("User has answered your questions:", "").split())[:600]


def render(path: str) -> str:
    out = ["# Session transcript (readable)", "",
           "Generated by `scripts/render_transcript.py` from the raw session log next to it. "
           "Tool output and hidden reasoning are omitted; proxy keys are redacted.", ""]
    last_stamp = ""
    tool_names = {}  # tool_use id -> tool name, to recognise the results worth keeping
    for line in open(path, encoding="utf-8"):
        try:
            rec = json.loads(line)
        except ValueError:
            continue
        kind, msg = rec.get("type"), rec.get("message")
        if kind not in ("user", "assistant") or not isinstance(msg, dict):
            continue
        content = msg.get("content")
        blocks = [{"type": "text", "text": content}] if isinstance(content, str) else (content or [])
        parts = []
        for b in blocks:
            if b.get("type") == "text":
                txt = clean_user(b["text"]) if kind == "user" else b["text"].strip()
                if txt:
                    parts.append(txt)
            elif b.get("type") == "tool_use" and kind == "assistant":
                tool_names[b.get("id")] = b.get("name")
                parts.append(tool_line(b))
            elif b.get("type") == "tool_result" and tool_names.get(b.get("tool_use_id")) in DECISION_TOOLS:
                parts.append(decision_line(tool_names[b["tool_use_id"]], result_text(b)))
        if not parts:
            continue
        stamp = ""
        if rec.get("timestamp"):
            try:
                stamp = datetime.fromisoformat(rec["timestamp"].replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M UTC")
            except ValueError:
                pass
        who = "USER" if kind == "user" else "CLAUDE"
        if kind == "user" or stamp != last_stamp:
            out += ["---", "", f"### {who}" + (f" · {stamp}" if stamp else ""), ""]
        else:
            out += [""]
        out += ["\n\n".join(parts), ""]
        last_stamp = stamp
    return redact("\n".join(out))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    md = render(sys.argv[1])
    if leaks(md):
        sys.exit("ABORT: sensitive string remains in rendered output")
    open(sys.argv[2], "w", encoding="utf-8").write(md)
    print(f"wrote {sys.argv[2]} ({len(md.splitlines())} lines)")
